"""Evaluation tasks supported by Optimus."""

from .countdown import (
    CountdownExample,
    answer_spans,
    assert_unique_example_ids,
    assert_unique_example_semantics,
    built_in_examples,
    extract_answer,
    extract_numeric_vote,
    load_examples,
    prompt,
    prompts,
    safe_eval_expr,
    score_completion,
    semantic_example_key,
    unique_example_count,
    unique_semantic_example_count,
    voted_answer_exact,
)
from .generation import GeneratedCountdown, generate_examples
from .prompt_variants import (
    UPSTREAM_SYSTEM_MESSAGE,
    bare_expression_prompt,
    compact_tagged_prompt,
    direct_tagged_prompt,
    make_variant_prompts,
    prompt_fn,
    reordered_tagged_prompt,
    tight_tagged_prompt,
    xml_tagged_prompt,
)

__all__ = [
    "CountdownExample",
    "GeneratedCountdown",
    "UPSTREAM_SYSTEM_MESSAGE",
    "answer_spans",
    "assert_unique_example_ids",
    "assert_unique_example_semantics",
    "bare_expression_prompt",
    "built_in_examples",
    "compact_tagged_prompt",
    "direct_tagged_prompt",
    "extract_answer",
    "extract_numeric_vote",
    "generate_examples",
    "load_examples",
    "make_variant_prompts",
    "prompt",
    "prompt_fn",
    "prompts",
    "reordered_tagged_prompt",
    "safe_eval_expr",
    "score_completion",
    "semantic_example_key",
    "tight_tagged_prompt",
    "unique_example_count",
    "unique_semantic_example_count",
    "voted_answer_exact",
    "xml_tagged_prompt",
]
