#!/usr/bin/env bash
set -euo pipefail

source .venv/bin/activate
export PYTHONUNBUFFERED=1
export VLLM_USAGE_STATS_ENABLED=${VLLM_USAGE_STATS_ENABLED:-0}
export VLLM_LOGGING_LEVEL=${VLLM_LOGGING_LEVEL:-ERROR}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-/tmp/optimus-xdg-config}
mkdir -p "$XDG_CONFIG_HOME"

TENSOR_PARALLEL_SIZE=${TENSOR_PARALLEL_SIZE:-8} \
POPULATIONS=${POPULATIONS:-"1024 4096"} \
PROMPTS=${PROMPTS:-64} \
HOLDOUT_PROMPTS=${HOLDOUT_PROMPTS:-256} \
PROMOTE=${PROMOTE:-64} \
CHUNK_ADAPTERS=${CHUNK_ADAPTERS:-8} \
MAX_LORAS=${MAX_LORAS:-8} \
MAX_CPU_LORAS=${MAX_CPU_LORAS:-8192} \
scripts/run_optimus_gpu_suite.sh
