#!/usr/bin/env bash
set -euo pipefail

source .venv/bin/activate
export PYTHONUNBUFFERED=1
export VLLM_USAGE_STATS_ENABLED=${VLLM_USAGE_STATS_ENABLED:-0}
export VLLM_LOGGING_LEVEL=${VLLM_LOGGING_LEVEL:-ERROR}
export VLLM_WORKER_MULTIPROC_METHOD=${VLLM_WORKER_MULTIPROC_METHOD:-spawn}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-/tmp/optimus-xdg-config}
if [[ -n "${OPTIMUS_VLLM_ATTENTION_BACKEND:-}" ]]; then
  export VLLM_ATTENTION_BACKEND="$OPTIMUS_VLLM_ATTENTION_BACKEND"
fi
mkdir -p "$XDG_CONFIG_HOME"

TENSOR_PARALLEL_SIZE=${TENSOR_PARALLEL_SIZE:-1} \
POPULATIONS=${POPULATIONS:-"1024 4096"} \
PROMPTS=${PROMPTS:-64} \
HOLDOUT_PROMPTS=${HOLDOUT_PROMPTS:-256} \
PROMOTE=${PROMOTE:-64} \
CHUNK_ADAPTERS=${CHUNK_ADAPTERS:-32} \
MAX_LORAS=${MAX_LORAS:-32} \
MAX_CPU_LORAS=${MAX_CPU_LORAS:-8192} \
KEEP_ADAPTERS=${KEEP_ADAPTERS:-0} \
scripts/run_optimus_gpu_suite.sh
