#!/usr/bin/env bash
set -euo pipefail

source .venv/bin/activate
export PYTHONUNBUFFERED=1
export VLLM_USAGE_STATS_ENABLED=${VLLM_USAGE_STATS_ENABLED:-0}
export VLLM_LOGGING_LEVEL=${VLLM_LOGGING_LEVEL:-ERROR}
export VLLM_WORKER_MULTIPROC_METHOD=${VLLM_WORKER_MULTIPROC_METHOD:-spawn}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-/tmp/optimus-xdg-config}
if [[ -n "${OPTIMUS_VLLM_ATTENTION_BACKEND:-}" ]]; then
  export VLLM_ATTENTION_BACKEND="$OPTIMUS_VLLM_ATTENTION_BACKEND"
fi
mkdir -p "$XDG_CONFIG_HOME"

RUN_HALVING=${RUN_HALVING:-0} \
KEEP_ADAPTERS=${KEEP_ADAPTERS:-1} \
MODEL=${MODEL:-Qwen/Qwen3-4B-Instruct-2507} \
DATA=${DATA:-data/countdown_generated_1200_seed20260507.json} \
TASKS=${TASKS:-ifeval} \
POPULATIONS=${POPULATIONS:-"128 256 512 1024 4096"} \
TENSOR_PARALLEL_SIZE=${TENSOR_PARALLEL_SIZE:-2} \
DATA_PARALLEL_SIZE=${DATA_PARALLEL_SIZE:-4} \
DTYPE=${DTYPE:-bfloat16} \
GPU_MEMORY_UTILIZATION=${GPU_MEMORY_UTILIZATION:-0.9} \
MAX_MODEL_LENGTH=${MAX_MODEL_LENGTH:-4096} \
MAX_NEW_TOKENS=${MAX_NEW_TOKENS:-64} \
PROMPT_VARIANTS=${PROMPT_VARIANTS:-bare} \
PROMPT_INPUT=${PROMPT_INPUT:-text} \
USE_CHAT_TEMPLATE=${USE_CHAT_TEMPLATE:-1} \
MAX_BASE_MALFORMED_FOR_SELECTION=${MAX_BASE_MALFORMED_FOR_SELECTION:-0.05} \
MAX_BASE_CAP_HIT_FOR_SELECTION=${MAX_BASE_CAP_HIT_FOR_SELECTION:-0.05} \
MIN_SELECTION_PROMPT_VARIANTS=${MIN_SELECTION_PROMPT_VARIANTS:-1} \
REQUIRE_ALL_PROMPT_VARIANTS_VALID=${REQUIRE_ALL_PROMPT_VARIANTS_VALID:-0} \
LIGHTEVAL_USE_CHAT_TEMPLATE=${LIGHTEVAL_USE_CHAT_TEMPLATE:-1} \
scripts/run_population_lighteval_pipeline.sh
